name: Lint Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Black
        run: pip install black

      - name: Verificar formato con Black
        run: |
          black --check --line-length=88 .

      - name: Mostrar diferencias si hay problemas de formato
        if: failure()
        run: |
          echo "❌ Código no está formateado correctamente"
          echo "💡 Ejecuta 'black --line-length=88 .' para auto-formatear"
          black --diff --line-length=88 .