name: Lint Flask App

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar flake8
        run: pip install flake8

      - name: Ejecutar lint con reglas personalizadas
        run: |
          flake8 . --ignore=E501,F401 --max-line-length=88
