name: Flask CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint con flake8
      run: |
        pip install flake8
        flake8 . || true  # No detiene el pipeline si hay errores (opcional)

    - name: Ejecutar pruebas con pytest
      run: |
        if [ -d "tests" ]; then
          pip install pytest
          pytest
        else
          echo "No hay pruebas definidas aún."
        fi
